name: Fabric Automation

on:
  workflow_dispatch:

env:
  CLIENT_ID: '8603d75c-5270-40ae-9df4-5e43ca13b965'
  TENANT_ID: 'd27e1d7c-3f35-4d28-a868-9e411f123b3a'
  SUBSCRIPTION_ID: 'd6f33ba3-12b4-4225-b854-b85d080936f6'

permissions:
  id-token: write  # REQUIRED for OIDC authentication
  contents: read

jobs:
  run-fabric-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get GitHub OIDC Token
        uses: actions/github-script@v7
        id: oidc
        with:
          script: |
            const token = await core.getIDToken('api://AzureADTokenExchange');
            core.setOutput('token', token);

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install Fabric CLI
        run: |
          pip install git+https://github.com/microsoft/fabric-cli.git

      - name: Run Fabric List
        run: |
          OIDC_TOKEN="${{ steps.oidc.outputs.token }}"
          fab config set encryption_fallback_enabled true         
          fab auth login -u ${{ env.CLIENT_ID }} --federated-token "$OIDC_TOKEN" --tenant ${{ env.TENANT_ID }}
          fab ls
          fab mkdir action.workspace -P capacityName=fcapa1