name: Fabric Automation

on:
  workflow_dispatch: 

permissions:
  id-token: write  # REQUIRED for OIDC authentication
  contents: read

jobs:
  run-fabric-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "8603d75c-5270-40ae-9df4-5e43ca13b965" 
          tenant-id: "d27e1d7c-3f35-4d28-a868-9e411f123b3a"  
          subscription-id: "d6f33ba3-12b4-4225-b854-b85d080936f6" 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install Fabric CLI
        run: |
          pip install git+https://github.com/microsoft/fabric-cli.git

      - name: Run Fabric List
        run: |
          TOKEN=$(az account get-access-token --resource "https://api.fabric.microsoft.com" --query accessToken -o tsv)
          fab auth login --token "$TOKEN"
          fab ls